name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: Target OS
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: Install dependencies
        run: npm install	
      - name: Run Test
        run: npm run test -- --coverage . --watchAll=false
      - name: Install SonarScanner
        run: npm install sonarqube-scanner --save-dev
      - name: SonarScanner Path
        run: echo "SONAR_SCANNER_PATH=$(pwd)/node_modules/sonarqube-scanner" >> $GITHUB_ENV
      - name: Run SonarScanner
        run: ${{ env.SONAR_SCANNER_PATH/bin/sonar-scanner }}
        env:
          SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
          SONAR_HOST_URL: "https://sonarcloud.io"
          SONAR_PROJECT_KEY: "jci-bms-platform-react"
    
