name: SonarCloud
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: Target OS
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: Install dependencies
        run: npm install	
      - name: Build React
        run: npm run build
      - name: Run Test
        run: npm run test -- --coverage . --watchAll=false
      - name: Download and Extract SonarScanner CLI
        run: |
          $url = 'https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-windows.zip'
          $output = 'sonar-scanner.zip'
          Invoke-WebRequest -Uri $url -OutFile $output
          Expand-Archive -Path $output -DestinationPath 'sonar-scanner'
      - name: Set SonarQube Scanner Home
        run: |
          echo "SONAR_SCANNER_HOME=$(pwd)/sonar-scanner" >> $GITHUB_ENV
      - name: Run SonarQube Analysis
        run: |
          .\sonar-scanner\bin\sonar-scanner.bat
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.coverageReportPaths=coverage/lcov.info
      - name: Download SonarCloud Report
        run: |
          curl -u $SONAR_TOKEN: -o sonarcloud_report.json "https://sonarcloud.io/api/measures/component?component=jci-bms-platform-react&metricKeys=coverage,bugs,vulnerabilities"
      - name: Store Analysis Report
        uses: actions/upload-artifact@v2
        with:
          name: sonarcloud-report
          path: sonarcloud_report.json
      - name: Display Analysis Report
        run: cat sonarcloud_report.json
