name: SonarCloud
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: Target OS
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: Install dependencies
        run: npm install	
      - name: Build React
        run: npm run build
      - name: Run Test
        run: npm run test -- --coverage . --watchAll=false
      - name: Install SonarScanner
        run: npm install -g sonarqube-scanner
      - name: SonarCloud Analysis
        run: sonar-scanner
        env:
          SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
          SONAR_HOST_URL: "https://sonarcloud.io"
          SONAR_PROJECT_KEY: "jci-bms-platform-react"
          SONAR_COVERAGE_REPORT_PATH: "coverage/lcov.info"
