name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: Target OS
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: Install dependencies
        run: npm install	
      - name: Run Test
        run: npm run test -- --coverage . --watchAll=false
      - name: Install Jest Sonar Reporter and Sonarqube Scanner
        run: npm install -D jest-sonar-reporter sonarqube-scanner
      - name: SonarCloud Analysis
        run: npm sonar-scanner -Dsonar.projectKey= jci-bms-platform-react -Dsonar.login=${{ env.SONAR_TOKEN }} -Dsonar.sources=. -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info
           
