name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: Install dependencies
        run: npm install		  
      - name: Install SonarCloud scanner
        run: |
          npm install -g sonarqube-scanner
          sonar-scanner --version
      - name: Run tests and collect coverage
        run: npm test -- --coverage --watchAll=false
      - name: SonarCloud analysis
        run: |
          sonar-scanner \
            -Dsonar.organization=jci-bms \
            -Dsonar.projectKey=jci-bms_jci-bms \
            -Dsonar.sources=src \
            -Dsonar.tests=src \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
