name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: Target OS
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: Install dependencies
        run: npm install	
      - name: Run Test
        run: npm run test -- --coverage . --watchAll=false
      - name: Install SonarScanner
        run: |
          $url = 'https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.1.2450.zip'
          $zipPath = "$env:USERPROFILE\sonar-scanner.zip"
          $extractPath = "$env:USERPROFILE\sonar-scanner"
          Invoke-WebRequest -Uri $url -OutFile $zipPath
          Expand-Archive -Path $zipPath -DestinationPath $extractPath
          $env:PATH += ";$extractPath\bin"
          Write-Host "Installed SonarScanner"
      - name: Run SonarScanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
